apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  labels:
    app: pythontest-approuter-app
  name: pythontest-apirule
  namespace: python-xsuaa
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: pythontest
  rules:
    - path: /.*
      methods: ["GET", "POST", "PUT", "DELETE"]
      service:
        name: pythontest-approuter-service
        port: 5000
      accessStrategies:
        - handler: allow