apiVersion: v1
kind: Service
metadata:
  labels:
    app: pythontest-approuter-app
  name: pythontest-approuter-service
  namespace: python-xsuaa 
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: pythontest-approuter-app